service: warzone-tracker

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  stage: dev
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    ACCEPT_SSO_FROM: ${env:ACCEPT_SSO_FROM}
    DATABASE_CONNECTION_STRING: ${env:DATABASE_CONNECTION_STRING}
    MAX_REPORTS_PER_USER: ${env:MAX_REPORTS_PER_USER}
    ADMIN_COMMANDS: ${env:ADMIN_COMMANDS}

package:
  individually: true
  exclude:
    - ./**

custom:
  serverless-offline:
    httpPort: 4000

functions:
  warzone-tracker-function:
    handler: dist/src/handler.handle
    memorySize: 256
    package:
      include:
        - dist/**
        - node_modules/**
    events:
      - http:
          path: warzone-tracker
          method: post
          cors: true
      - schedule:
          rate: rate(1 minute)
          enabled: true
          input:
            scheduleCommand: '/ReportLastMatches'
