version: 2.1

jobs:
  integration:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run tests
          command: yarn test:unit:ci

  deploy:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy application
          command: yarn deploy:production
      - run:
          name: Set webhook
          command: |
            URL="$(yarn serverless info --stage production --verbose | grep ServiceEndpoint | sed s/ServiceEndpoint\:\ //g)"
            echo "Webhook: $URL"
            ./setTelegramWebhook.sh $URL/warzone-tracker $TELEGRAM_BOT_TOKEN
workflows:
  build:
    jobs:
      - integration
      - deploy:
          context: LAMBDA
          requires:
            - integration
          filters:
            branches:
              only:
                - main